// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCcBp8wOfH8GWQXjdsudWBN83JvWjiQWFU',
    appId: '1:530304903122:web:8bdb8080fa85f8713d0a0b',
    messagingSenderId: '530304903122',
    projectId: 'ecoeagle-1ff39',
    authDomain: 'ecoeagle-1ff39.firebaseapp.com',
    storageBucket: 'ecoeagle-1ff39.firebasestorage.app',
    measurementId: 'G-Q0WXMB9W9H',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyALTdhdCQ9Et3DigdPHkSE7mPIO7l2Wtuo',
    appId: '1:530304903122:android:054d7dcb9c3696e93d0a0b',
    messagingSenderId: '530304903122',
    projectId: 'ecoeagle-1ff39',
    storageBucket: 'ecoeagle-1ff39.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCT1K9jme-Xu3DqfK9O0-VzL0LlRzPy6uc',
    appId: '1:530304903122:ios:49ab657e3f032c763d0a0b',
    messagingSenderId: '530304903122',
    projectId: 'ecoeagle-1ff39',
    storageBucket: 'ecoeagle-1ff39.firebasestorage.app',
    iosBundleId: 'com.example.ecoeagle',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCT1K9jme-Xu3DqfK9O0-VzL0LlRzPy6uc',
    appId: '1:530304903122:ios:49ab657e3f032c763d0a0b',
    messagingSenderId: '530304903122',
    projectId: 'ecoeagle-1ff39',
    storageBucket: 'ecoeagle-1ff39.firebasestorage.app',
    iosBundleId: 'com.example.ecoeagle',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCcBp8wOfH8GWQXjdsudWBN83JvWjiQWFU',
    appId: '1:530304903122:web:9266ba713e65e0783d0a0b',
    messagingSenderId: '530304903122',
    projectId: 'ecoeagle-1ff39',
    authDomain: 'ecoeagle-1ff39.firebaseapp.com',
    storageBucket: 'ecoeagle-1ff39.firebasestorage.app',
    measurementId: 'G-3FFKH40WN7',
  );
}
